const RestaurantData = [
  {
    id: '123456',
    name: 'Pizza Paradise',
    image:
      'RX_THUMBNAIL/IMAGES/VENDOR/2025/6/17/6def0f0f-9e6c-45c0-b5e6-05af750f27b5_795906.JPG',
    locality: 'MG Road',
    area: 'Central District',
    costForTwo: '₹400 for two',
    cuisines: [],
    rating: 4.3,
    totalRatings: '10K+ ratings',
    isVeg: false,
    deliveryTime: null,
    discount: '50% OFF UPTO ₹100',
  },
  {
    id: '234567',
    name: 'Burger Hub',
    image:
      'RX_THUMBNAIL/IMAGES/VENDOR/2024/6/24/acfcaacc-edf0-4189-8264-d614d312c0ee_740457.JPG',
    locality: 'Park Street',
    area: 'Downtown',
    costForTwo: '₹300 for two',
    cuisines: ['Burgers', 'American', 'Fast Food'],
    rating: 4.5,
    totalRatings: '15K+ ratings',
    isVeg: false,
    deliveryTime: 25,
    discount: '40% OFF UPTO ₹80',
  },
  {
    id: '345678',
    name: 'Green Bites',
    image: 'e0839ff574213e6f35b3899ebf1fc597',
    locality: 'Residency Road',
    area: 'South Zone',
    costForTwo: '₹250 for two',
    cuisines: ['Healthy Food', 'Salads', 'Vegan'],
    rating: 4.7,
    totalRatings: '8K+ ratings',
    isVeg: true,
    deliveryTime: 20,
    discount: '30% OFF UPTO ₹75',
  },
  {
    id: '456789',
    name: 'Spice Kingdom',
    image: 'rng/md/carousel/production/indian101',
    locality: 'Brigade Road',
    area: 'City Center',
    costForTwo: '₹500 for two',
    cuisines: ['Indian', 'North Indian', 'Biryani'],
    rating: 4.2,
    totalRatings: '12K+ ratings',
    isVeg: false,
    deliveryTime: 35,
    discount: '20% OFF UPTO ₹50',
  },
  {
    id: '567890',
    name: 'Chinese Dragon',
    image:
      'RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/ba9f1f59-30d5-44de-afad-df6db8471ead_9648.jpg',
    locality: 'Commercial Street',
    area: 'East District',
    costForTwo: '₹350 for two',
    cuisines: ['Chinese', 'Asian', 'Thai'],
    rating: 4.4,
    totalRatings: '9K+ ratings',
    isVeg: false,
    deliveryTime: 28,
    discount: '60% OFF UPTO ₹120',
  },
];

export default RestaurantData;
